
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWordReplacements(replacements: WordReplacement[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_word_replacements", { replacements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomProfileCommands(commands: WordReplacement[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_profile_commands", { commands }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSystemAudioApp(appName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_system_audio_app", { appName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the executable names of apps that currently have an audio session
 * (Windows only — used to populate the per-app capture selector).
 */
async listSystemAudioApps() : Promise<string[]> {
    return await TAURI_INVOKE("list_system_audio_apps");
},
async changeClipboardOnlySetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_only_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLiveAutoPasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_live_auto_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: AppTheme) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAccentColorSetting(color: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_accent_color_setting", { color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAccentTintSurfacesSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_accent_tint_surfaces_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSourceAttributionSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_source_attribution_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLiveModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_live_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLiveModeSystemSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_live_mode_system_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTourCompletedSetting(completed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_tour_completed_setting", { completed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWorkProfileSetting(profile: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_work_profile_setting", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDictationStatsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_dictation_stats_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteInCallsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_in_calls_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWakeWordSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wake_word_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWakeWordSamplesSetting(samples: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wake_word_samples_setting", { samples }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records the user saying the wake word once and stores its acoustic
 * fingerprint. Returns how many recordings are now stored.
 */
async captureWakeWordSample() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_wake_word_sample") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes every recording, so the user can start teaching from scratch.
 */
async clearWakeWordRecordings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_wake_word_recordings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * How many recordings are stored, for the settings screen.
 */
async countWakeWordRecordings() : Promise<number> {
    return await TAURI_INVOKE("count_wake_word_recordings");
},
/**
 * Sends the mute key once so the user can bind it in Discord: no physical
 * keyboard has an F13 to press while Discord waits for a keybind.
 */
async sendCallMuteKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_call_mute_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUiFontSetting(font: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ui_font_setting", { font }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUiFontSizeSetting(size: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ui_font_size_setting", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperAcceleratorSetting(accelerator: WhisperAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * whisper.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
/**
 * True when this copy came from the Microsoft Store. The Store manages its
 * own updates, so the app must not offer or perform any of its own.
 */
async isPackaged() : Promise<boolean> {
    return await TAURI_INVOKE("is_packaged");
},
/**
 * `None` when this copy and the installer agree on where the app lives, which
 * is the normal case. See install_check.rs for what a mismatch means.
 */
async installLocationMismatch() : Promise<InstallMismatch | null> {
    return await TAURI_INVOKE("install_location_mismatch");
},
/**
 * Both folders for the debug panel, agreeing or not. Answers in dev builds
 * too, where `install_location_mismatch` deliberately stays quiet.
 */
async installPaths() : Promise<InstallPaths> {
    return await TAURI_INVOKE("install_paths");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Whether an Ollama server is reachable on its default local port.
 * 
 * Called before turning post-processing on for the first time: VoCript's
 * whole pitch is "100% local", so the provider that setting starts on should
 * not be a cloud one just because it happened to be first in the list.
 * `/api/tags` (not `/v1/models`) because it is Ollama's own lightweight
 * health-style endpoint — answers instantly without touching the model
 * registry, so a cold Ollama start does not make this feel like a hang.
 */
async detectLocalPostProcessProvider() : Promise<boolean> {
    return await TAURI_INVOKE("detect_local_post_process_provider");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import an existing model file or directory (e.g. from a previous Handy
 * install or any folder) into VoCript by hard-linking it — reusing the same
 * bytes on disk instead of re-downloading. Returns the resulting model id.
 */
async importModelFromPath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_model_from_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrayMenuState() : Promise<Result<TrayMenuState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tray_menu_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runs an action picked in the custom menu window. Same ids as the native
 * menu items, so both menus share one code path.
 */
async trayMenuAction(action: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_menu_action", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the menu UI once it knows how tall its content is, so the window
 * hugs the content instead of leaving empty space below it.
 */
async resizeTrayMenu(height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_tray_menu", { height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan common locations on the computer for speech models that already exist,
 * so the user can reuse them without downloading again.
 */
async scanForExternalModels() : Promise<Result<FoundModel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_for_external_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decode an arbitrary audio/video file and transcribe it to text + SRT.
 * 
 * Runs on a blocking worker thread (not the UI thread) so a long file won't
 * freeze the window. The model is loaded on demand if not already in memory,
 * using the user's currently selected model and language.
 */
async transcribeFile(path: string) : Promise<Result<FileTranscriptionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save UTF-8 text (e.g. a transcription or SRT) to an arbitrary path chosen
 * by the user via the save dialog. Done on the backend to avoid having to
 * widen the frontend filesystem scope beyond `$APPDATA`.
 */
async saveTextFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_text_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a UTF-8 text file chosen by the user via the open dialog (e.g. a CSV to
 * import into the personal dictionary). Done on the backend to avoid widening
 * the frontend filesystem scope beyond `$APPDATA`. Tolerates invalid bytes and
 * strips a leading UTF-8 BOM (Excel often adds one).
 */
async readTextFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_text_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a recording's WAV bytes and return them base64-encoded.
 * 
 * The recordings live under the app data dir, which the frontend `fs` scope
 * does not reliably grant access to on Windows (`readFile` returns "forbidden
 * path"). Reading the file on the backend — which has full disk access — and
 * handing the bytes to the webview as base64 sidesteps both the `fs` scope and
 * the `asset://` protocol, which have both been unreliable for this path.
 */
async getAudioFileData(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_data", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDictationStats() : Promise<DictationStats> {
    return await TAURI_INVOKE("get_dictation_stats");
},
async resetDictationStats() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_dictation_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Typing speed the "time saved" figure is measured against, so the UI states
 * the assumption instead of presenting the number as an absolute truth.
 */
async getTypingWpmBaseline() : Promise<number> {
    return await TAURI_INVOKE("get_typing_wpm_baseline");
},
async getSystemFonts() : Promise<string[]> {
    return await TAURI_INVOKE("get_system_fonts");
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current OS theme ("light"/"dark"). On Windows it reads the registry value
 * `AppsUseLightTheme`, because WebView2 does not reliably expose
 * `prefers-color-scheme`; the frontend uses this to resolve the "system" theme.
 */
async getSystemTheme() : Promise<string> {
    return await TAURI_INVOKE("get_system_theme");
},
/**
 * Forgets the dragged position, so the overlay goes back to following
 * `overlay_position` (top/bottom, tracking the active monitor) on its own.
 */
async resetOverlayPosition() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_overlay_position") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the overlay has ever been dragged, for the settings screen to show
 * (or hide) the "reset position" action.
 */
async hasCustomOverlayPosition() : Promise<boolean> {
    return await TAURI_INVOKE("has_custom_overlay_position");
},
/**
 * True cuando este binario trae las funciones de pago dentro.
 * 
 * No dice si están desbloqueadas, solo si existen: sirve para que la interfaz sepa si debe
 * enseñar siquiera la pantalla donde se pega la licencia.
 */
async proIsAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("pro_is_available");
},
/**
 * El estado de la licencia guardada en este equipo.
 */
async proLicenseStatus() : Promise<EstadoLicencia> {
    return await TAURI_INVOKE("pro_license_status");
},
/**
 * Guarda una licencia si es válida y da de alta este ordenador en la nube.
 * 
 * El orden: primero la firma en local (sin eso no hay nada que hablar con nadie), después
 * la nube, y solo si la nube no la rechaza se guarda. Si no hay red, se guarda igual y se
 * deja apuntado que hay que avisar a la nube al arrancar: una licencia buena no puede
 * depender de tener conexión en ese preciso momento.
 */
async proActivateLicense(clave: string) : Promise<Result<EstadoLicencia, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_activate_license", { clave }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Quita la licencia de este equipo, por ejemplo para llevársela a otro.
 * 
 * Avisa a la nube para liberar el hueco, pero no espera a que conteste para borrar: quien
 * quita una licencia quiere que desaparezca ahora, con red o sin ella.
 */
async proDeactivateLicense() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_deactivate_license") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lee el texto que haya dentro del recuadro y lo devuelve.
 */
async proReadRegion(region: Region) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_read_region", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lee el texto del recuadro y lo dice en voz alta.
 * 
 * Devuelve también el texto: la interfaz lo enseña mientras suena, que es lo que deja claro
 * que ha leído lo que tocaba cuando la voz se equivoca de palabra.
 */
async proReadAloud(region: Region) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_read_aloud", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abre la mirilla y devuelve el recuadro que se arrastre, o nada si se cancela.
 */
async proPickRegion() : Promise<Result<Region | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_pick_region") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * La función completa: señalas un trozo de pantalla y VoCript te lo lee en voz alta.
 * 
 * Es un solo comando y no tres encadenados desde el frontend a propósito. Entre señalar y
 * oír no hay ninguna decisión que tomar, y partirlo obligaría a que la interfaz supiera de
 * recuadros, capturas y motores de voz para nada.
 * 
 * Devuelve `None` cuando la persona se arrepiente, que no es un error y no debe pintar uno.
 */
async proReadAloudPick() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_read_aloud_pick") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Si este Windows tiene voz con la que leer.
 * 
 * La interfaz lo pregunta antes de ofrecer la lectura, para avisar en los ajustes y no a
 * mitad de la función.
 */
async proHasVoice() : Promise<boolean> {
    return await TAURI_INVOKE("pro_has_voice");
},
/**
 * Lee en voz alta toda la pantalla donde está el puntero, sin señalar nada.
 * 
 * Para cuando lo que quieres oír es lo que hay delante y no un trozo: un artículo, un
 * correo abierto, una página. Sale más texto y alguna palabra suelta de la interfaz, pero
 * ahorra el arrastre.
 */
async proReadAloudScreen() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_read_aloud_screen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Vuelve a leer el último recuadro que se señaló.
 * 
 * Relee la pantalla en vez de guardar el texto: si lo que había ahí ha cambiado, lo que se
 * espera oír es lo de ahora, no lo de hace un minuto.
 */
async proReadAloudAgain() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_read_aloud_again") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Si hay algo que repetir, para que el botón no aparezca cuando no sirve de nada.
 */
async proCanRepeat() : Promise<boolean> {
    return await TAURI_INVOKE("pro_can_repeat");
},
/**
 * Deja la voz a media frase.
 */
async proPauseSpeaking() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_pause_speaking") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sigue por donde se quedó.
 */
async proResumeSpeaking() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_resume_speaking") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * El atajo que abre la mirilla ahora mismo.
 */
async proGetHotkey() : Promise<string> {
    return await TAURI_INVOKE("pro_get_hotkey");
},
/**
 * Cambia el atajo de leer, y lo deja funcionando sin reiniciar.
 */
async proSetHotkey(atajo: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_set_hotkey", { atajo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manda callar a la voz.
 * 
 * No exige licencia a propósito: si por lo que sea la voz está sonando, poder pararla nunca
 * puede depender de una comprobación que podría fallar.
 */
async proStopSpeaking() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_stop_speaking") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * El agente, primer paso: mira la pantalla y cuenta lo que ve.
 * 
 * Todavía no actúa ni entiende, solo lee la pantalla donde está el puntero y devuelve el
 * texto. Es el trozo que hay que tener funcionando antes de que un modelo decida nada,
 * porque el resto del agente se construye encima de esto.
 */
async proAgentSee() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_agent_see") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * El agente: dictas un encargo y lo resuelve mirando lo que tienes en pantalla.
 * 
 * Devuelve el texto listo para escribir. Quien lo llama decide si lo pega, lo enseña o lo
 * dice en voz alta: eso no es cosa del agente.
 */
async proAgentDo(encargo: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_agent_do", { encargo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lo que la nube sabe de esta licencia: dispositivos y uso del mes.
 */
async proCloudStatus() : Promise<Result<EstadoNube, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_cloud_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Da de baja un ordenador de la lista, para dejar sitio a otro.
 */
async proRemoveDevice(id: string) : Promise<Result<Dispositivo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_remove_device", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Si la limpieza del habla está encendida y va por la nube de Pro.
 */
async proCloudCleanupEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("pro_cloud_cleanup_enabled");
},
/**
 * Enciende o apaga la limpieza del habla por la nube de Pro.
 */
async proSetCloudCleanup(activa: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_set_cloud_cleanup", { activa }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * El atajo del agente ahora mismo.
 */
async proGetAgentHotkey() : Promise<string> {
    return await TAURI_INVOKE("pro_get_agent_hotkey");
},
/**
 * Cambia el atajo del agente, y lo deja funcionando sin reiniciar.
 */
async proSetAgentHotkey(atajo: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_set_agent_hotkey", { atajo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Empieza o termina un encargo dictado desde un botón, sin atajo.
 * 
 * Siempre alterna (una pulsación empieza, otra termina), sea cual sea el gesto que la
 * persona tenga puesto para los atajos: un botón no se puede mantener pulsado.
 */
async proAgentToggle() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pro_agent_toggle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload
}>({
historyUpdatePayload: "history-update-payload"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; track_dictation_stats?: boolean; 
/**
 * What this user's own model writes when they say the wake word.
 * 
 * Speech models have never seen "VoCript" and spell it differently every
 * time — real captures include "Ball Crypto" and "All crypt". Rather than
 * guessing every spelling, the user says the word a few times and whatever
 * their model produces is stored here as the thing to listen for. It adapts
 * to their voice, accent, microphone and model at once.
 */
wake_word_samples?: string[]; 
/**
 * Listen continuously for the word "VoCript" and start dictating on it.
 * Off by default: it keeps the microphone open, which is not something to
 * switch on for someone without asking.
 */
wake_word_enabled?: boolean; 
/**
 * Hold F13 down while dictating so voice-chat apps bound to it (Discord's
 * "push to mute") stop transmitting. The microphone itself is never muted:
 * VoCript would stop hearing the user too.
 */
mute_in_calls?: boolean; 
/**
 * Id of the UI font stack (see src/lib/constants/fonts.ts). Only fonts the
 * OS already has: a restrictive CSP means nothing can be downloaded.
 */
ui_font?: string; 
/**
 * Root font size in px. Everything else is sized in rem, so this scales
 * the whole interface.
 */
ui_font_size?: number; selected_model?: string; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; 
/**
 * Executable name of the app to capture for system-audio transcription
 * (e.g. "Spotify.exe"). `None` = capture the whole system mix.
 */
system_audio_app?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; overlay_custom_position?: OverlayCustomPosition | null; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; 
/**
 * Personal dictionary: deterministic exact replacements (from -> to).
 */
word_replacements?: WordReplacement[]; 
/**
 * Voice→symbol commands of the "custom" professional profile. Only applied
 * when `work_profile == "custom"`. Separate from `word_replacements`, which
 * always applies regardless of profile.
 */
custom_profile_commands?: WordReplacement[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; clipboard_only?: boolean; 
/**
 * Live transcription: when true, the final text is pasted into the active
 * app automatically when the live session stops (like normal dictation).
 * When false, the text stays in an editable bubble and the user copies it
 * manually with the copy button.
 */
live_auto_paste?: boolean; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; 
/**
 * Apariencia de la interfaz: seguir el sistema, claro u oscuro.
 */
theme?: AppTheme; 
/**
 * Color de acento de la interfaz (hex, p. ej. "#3b82f6"). Tema de color.
 */
accent_color?: string; 
/**
 * Si el acento tiñe además los fondos, paneles y separadores, en vez de
 * pintar solo botones e interruptores. Activado por defecto: es lo que da
 * al tema elegido presencia en toda la ventana.
 */
accent_tint_surfaces?: boolean; 
/**
 * Al transcribir audio del sistema, añade al final una línea de «Fuente»
 * con lo que sonaba (título, artista/canal, app y minuto), vía SMTC.
 */
source_attribution?: boolean; 
/**
 * «Modo en vivo» (voz): cuando está activo, el atajo de dictado normal
 * (`transcribe`) muestra la cápsula en vivo en vez de pegar al final.
 */
live_mode?: boolean; 
/**
 * «Modo en vivo» (audio del sistema): cuando está activo, el atajo de
 * audio del sistema (`transcribe_system`) muestra la cápsula en vivo.
 */
live_mode_system?: boolean; 
/**
 * True una vez que el usuario ha completado (o saltado) el tour guiado de
 * bienvenida. Evita que vuelva a aparecer solo; el botón «Guía» lo relanza.
 */
tour_completed?: boolean; 
/**
 * Perfil de trabajo elegido en el onboarding (p. ej. "writing", "coding",
 * "meetings", "multilingual"). `None` = el usuario lo configura a mano.
 */
work_profile?: string | null; experimental_enabled?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; whisper_accelerator?: WhisperAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; whisper_gpu_device?: number; extra_recording_buffer_ms?: number }
/**
 * Apariencia de la interfaz. `System` sigue la preferencia del sistema
 * operativo (claro/oscuro); `Light` y `Dark` fuerzan el tema elegido.
 */
export type AppTheme = "system" | "light" | "dark"
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { whisper: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type DayStat = { 
/**
 * Local calendar day, `YYYY-MM-DD`.
 */
day: string; words: number; seconds: number; sessions: number }
export type DictationStats = { 
/**
 * One entry per day that has any dictation, oldest first.
 */
days: DayStat[]; total_words: number; total_seconds: number; total_sessions: number; 
/**
 * Consecutive days up to today (yesterday still counts: the streak only
 * breaks once a full day goes by with nothing dictated).
 */
current_streak: number; longest_streak: number; best_day: DayStat | null }
/**
 * Un ordenador dado de alta en la nube con una licencia.
 */
export type Dispositivo = { id: string; nombre: string; 
/**
 * Fecha de alta, AAAA-MM-DD.
 */
alta: string }
export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere" | 
/**
 * Runs on `transcribe-cpp` (GGUF/GGML) instead of `transcribe-rs` (ONNX) —
 * a second, coexisting inference engine for models only Handy's newer
 * GGUF catalog publishes (e.g. Nemotron, Parakeet Unified).
 */
"TranscribeCpp"
/**
 * Lo que la interfaz necesita saber de una licencia, sin exponerle nada de criptografía.
 */
export type EstadoLicencia = { 
/**
 * La única que decide si las funciones de pago se ven o no.
 */
activa: boolean; correo: string | null; expira: string | null; 
/**
 * Por qué no vale, en un texto que se le pueda enseñar a una persona.
 */
motivo: string | null }
/**
 * Lo que la nube sabe de esta licencia, para enseñarlo en la pantalla de Pro.
 */
export type EstadoNube = { dispositivos: Dispositivo[]; tope_dispositivos: number; tokens_usados: number; cuota_tokens: number; 
/**
 * El id de este ordenador, para marcarlo en la lista y no dejar que se quite a sí mismo
 * sin querer.
 */
este_dispositivo: string }
/**
 * Result of transcribing an imported audio/video file. Both the plain text
 * and the SRT subtitle string are returned so the UI can offer either.
 */
export type FileTranscriptionResult = { text: string; srt: string; duration_secs: number }
/**
 * A speech model found elsewhere on the computer that can be reused by VoCript
 * without re-downloading. Returned by `scan_for_external_models`.
 */
export type FoundModel = { 
/**
 * Absolute path to the existing model file or directory.
 */
path: string; 
/**
 * Id of the predefined model this file corresponds to, if recognized.
 */
suggested_id: string | null; 
/**
 * Human-readable name for display.
 */
name: string; 
/**
 * Approximate size in MB.
 */
size_mb: number; 
/**
 * Whether the model is a directory (e.g. Parakeet) vs a single .bin file.
 */
is_directory: boolean; 
/**
 * True if this path is already inside VoCript's own models directory.
 */
already_imported: boolean }
export type GpuDeviceOption = { id: number; name: string; total_vram_mb: number }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
/**
 * A running copy and an update target that are not the same folder.
 */
export type InstallMismatch = { 
/**
 * Folder the running executable lives in.
 */
running_from: string; 
/**
 * Folder the installer would write the update to.
 */
updates_go_to: string }
/**
 * The two folders, whether or not they agree, for the debug panel to show.
 */
export type InstallPaths = { 
/**
 * Folder the running executable lives in.
 */
running_from: string; 
/**
 * Folder the installer would write to, or `None` when nothing claims one
 * (portable copies, Scoop, a dev build, anything but Windows).
 */
updates_go_to: string | null }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; sha256: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null; 
/**
 * How long the last dictation took to transcribe, in milliseconds, or
 * `None` if nothing has been transcribed since the app started.
 */
last_transcription_ms: number | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
/**
 * Where the user last dragged the overlay to, in physical pixels. `None`
 * means it has never been dragged, so `overlay_position` (top/bottom, and
 * which monitor to follow) still decides where it appears. Once set, it wins
 * over that automatic placement until the user drags it again or resets it.
 */
export type OverlayCustomPosition = { x: number; y: number }
export type OverlayPosition = "none" | "top" | "bottom"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * Un rectángulo en coordenadas de escritorio, tal cual las da el sistema.
 * 
 * Físicas, no lógicas: con dos monitores a escalas distintas, las lógicas de uno no
 * significan lo mismo que las del otro y el recorte se va de sitio.
 */
export type Region = { x: number; y: number; ancho: number; alto: number }
export type SecretMap = Partial<{ [key in string]: string }>
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
export type TrayMenuLanguage = { code: string; native_name: string; is_active: boolean }
export type TrayMenuModel = { id: string; name: string; is_active: boolean }
export type TrayMenuState = { version_label: string; live_voice: boolean; live_system: boolean; model_loaded: boolean; is_busy: boolean; update_checks_enabled: boolean; models: TrayMenuModel[]; active_model_name: string | null; languages: TrayMenuLanguage[]; active_language_native: string; 
/**
 * Newer version found by the daily background check, if any. Just the
 * number: the menu shows it beside "Check for updates", which is already
 * translated.
 */
available_update: string | null }
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type WhisperAcceleratorSetting = "auto" | "cpu" | "gpu"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }
/**
 * A personal-dictionary entry: replace exact occurrences of `from` with `to`
 * in the transcribed text. Deterministic (unlike the fuzzy `custom_words`).
 */
export type WordReplacement = { from: string; to: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
